# Generated by Django 4.1 on 2022-08-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_almuerzo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('asunto', models.CharField(max_length=100, verbose_name='Asunto')),
                ('descripcion', models.TextField(max_length=1000, verbose_name='Descripcion')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
    ]
